<Project>
  <ItemGroup>
    <!-- App -->
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="Dirkster.AvalonDock" Version="4.74.1" />
    <PackageVersion Include="Dirkster.AvalonDock.Themes.VS2013" Version="4.74.1" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Windows.Console.ConPTY" Version="1.24.260710001" />
    <PackageVersion Include="System.Management" Version="10.0.12" />
    <!-- Terminal -->
    <PackageVersion Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageVersion Include="Wcwidth" Version="4.0.1" />
    <!-- Tests -->
    <PackageVersion Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.10.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>
